### ISSUE TITLE
[Feature Request] Allow configurable data directory, port, etc without editing package source

### ISSUE THREAD

**Issue by alshayed** [withcatai/catai#10]
It would be nice to allow people to specify settings like data directory & port to use instead of hard-coded values without editing the package source.

**Comment by ido-pluto** [comment]
This is a useful idea,
In the feature I would add support to configuration via environment variables

Thanks for sharing

**Comment by ido-pluto** [comment]
Configuring the `data directory` is challenging because `catai` will not know where to search the settings. 
It was like that in some previous versions, but with every update, all the internal data was deleted (stored inside the package).

What is your use case for that?
There may be a workaround...

For other simple configurations like port, open in browser and etc... I added support in the recent version (0.3.4)
Docs will be added soon :)

**Comment by alshayed** [comment]
Thanks for looking at this. Note I haven't looked at your updates yet, but for the data directory TBH my "use case" is just that I don't like having everything in my home directory LOL.

Here's the patch I made for my own use to have it use environment variables if they exist, I use npm patch-package for this sort of thing and just installed catai in a folder with npm install instead of doing it globally. However I wasn't sure if everything was using that DOWNLOAD_LOCATION constant or if other things were possibly doing something on their own.

Another thought you could consider is putting a config file in the users $HOME/.config directory per the XDG specification, but maybe only if catai was installed globally instead of in a normal folder. I'm not sure how you would know that at runtime though. 

```
diff --git a/node_modules/catai/src/config.js b/node_modules/catai/src/config.js
index 36fa3de..8a4dbbc 100644
--- a/node_modules/catai/src/config.js
+++ b/node_modules/catai/src/config.js
@@ -1,6 +1,6 @@
-export const PORT = 3000;
+export const PORT = (typeof process.env?.CATAI_PORT === 'undefined') ? 3000 : parseInt(process.env.CATAI_PORT);

-export const OPEN_IN_BROWSER = true;
+export const OPEN_IN_BROWSER = (typeof process.env?.CATAI_OPEN_BROWSER === 'undefined') ? true : (process.env.CATAI_OPEN_BROWSER === 'true');

 export const SELECTED_BINDING = 'node-llama' || 'alpaca-cpp';

diff --git a/node_modules/catai/src/model-settings.js b/node_modules/catai/src/model-settings.js
index ac004d0..95c42db 100644
--- a/node_modules/catai/src/model-settings.js
+++ b/node_modules/catai/src/model-settings.js
@@ -2,7 +2,7 @@ import fs from 'fs-extra';
 import path from 'path';
 import os from 'os';

-export const DOWNLOAD_LOCATION = path.join(os.homedir(), 'catai');
+export const DOWNLOAD_LOCATION = (typeof process.env?.CATAI_DATA_DIR === 'undefined') ? path.join(os.homedir(), 'catai') : process.env.CATAI_DATA_DIR;

 const modelSettings = path.join(DOWNLOAD_LOCATION, 'settings.json');
 await fs.ensureFile(modelSettings);
```

**Comment by ido-pluto** [comment]
This is probably the best solution, but you need to export your env variable to the .bash_profile or enter it every time.
Moreover, it needs to be done before the first installation of catai.

Will be added in the next version
