### ISSUE TITLE
Fetch is not defined

### ISSUE THREAD

**Issue by ilisparrow** [withcatai/catai#11]
Hello, 

Thank you for your work. 
I have some problems setting it up. 

When I try to download a model I get this error : 
![image](https://user-images.githubusercontent.com/4880273/236707426-c1cf5281-69ca-4357-a350-c3d0be3d0a01.png)

I tried to install node-fetch@2 and node-fetch without much success. 

Do you have an Idea of what the problem might be ?

I am on Ubuntu 22.04 LTS

**Comment by ido-pluto** [comment]
Which version of nodejs are you running?

```
node -v
``` 

I recommend installing the 19 version.
You can use [nvm](https://github.com/nvm-sh/nvm) for that task

```
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
nvm install 19
```

**Comment by ilisparrow** [comment]
Hello, 
Thank you. 
You are right.
It works :)
