### ISSUE TITLE
Can't set CATAI_OPEN_IN_BROWSER to false

### ISSUE THREAD

**Issue by rakete** [withcatai/catai#13]
The `|| true` in this line: 

https://github.com/ido-pluto/catai/blob/c53b1b2dc6af8bcbbaf53c9a0d4e45f1187b2caf/server/src/config.js#L4

prevents setting CATAI_OPEN_IN_BROWSER to anything other then true. When it's set to false it will default to || true.

**Comment by ido-pluto** [comment]
Thanks for reporting!
Yes, this avoids the purpose of default.
In the meantime change the `||` to `??`.

It will be fixed in the next version :)

**Comment by ido-pluto** [comment]
Checkout version 0.3.8
