### ISSUE TITLE
Multiple files in a model?

### ISSUE THREAD

**Issue by pomazanbohdan** [withcatai/catai#14]
https://huggingface.co/mosaicml/mpt-7b-chat/tree/main

![image](https://github.com/ido-pluto/catai/assets/696713/207d45aa-3ec6-4795-8975-635a11d5b83a)

**Comment by ido-pluto** [comment]
We currently support only ggml quantization, best support with q4_0

**Comment by pomazanbohdan** [comment]
Good model - mpt, only recently appeared in ggml format
https://huggingface.co/models?sort=downloads&search=mpt+ggml

**Comment by ido-pluto** [comment]
I am currently working on multi binding that will allow more models that are not supported by llama.cpp, (such as this model)

**Comment by ido-pluto** [comment]
There is support for multiple files in a model from version 1, but only ggml format is support
