### ISSUE TITLE
GPT4All-13B requires basic auth

### ISSUE THREAD

**Issue by mledwards** [withcatai/catai#20]
The fetch URL for GPT4All-13B (and a few others) requires a basic auth, so isn't downloadable from the models menu:
https://huggingface.co/Pi3141/alpaca-GPT4All-13BB-ggml/resolve/main/ggml-model-q4_0.bi

Also, is the end meant to be `.bin` like the others?

**Comment by ido-pluto** [comment]
Update CatAI and try again. there was a problem with the installation

**Comment by mledwards** [comment]
That's downloading now, thanks! I'm struggling a bit with getting it working, I commented in another thread with a screenshot and you said you were fixing something. Happy to close this one, as it's only related to the downloading.

**Comment by ido-pluto** [comment]
I tested the model on my machine. If it does not work please share a screenshot and I will try to help you :)

**Comment by mledwards** [comment]
Oh, that's all working today! It's slooow on my machine, but we'll be provisioning a server to test it properly. Thanks again man!
