### ISSUE TITLE
API response

### ISSUE THREAD

**Issue by mledwards** [withcatai/catai#21]
It looks like the API streams the whole result to the server console before sending the output back as the response. Is there a way to return the results as soon as they're available?

Or if not, then to stream the results back from the API?

**Comment by ido-pluto** [comment]
Currently there is the API of the ui, that works with Web-Sockets, but it is more complex and not documented yet.

You can check the example used in this file:
https://github.com/ido-pluto/catai/blob/main/client/catai/src/utils/chat.ts

**Comment by ido-pluto** [comment]
There is a new API that supports streaming, checkout the docs
