### ISSUE TITLE
Error on local setup

### ISSUE THREAD

**Issue by authcompanion** [withcatai/catai#22]
Hello 👋  
In following [development.md](https://github.com/ido-pluto/catai/blob/main/docs/development.md) to run the Server locally, I'm getting the following error below when starting the Server. Would you have any advice for me to troubleshoot further? 

Repro:
- Clone repo
cd server
npm install
npm run install-model Vicuna-7B
npm start

Error:
zsh: segmentation fault  npm start

`Node- v18.16.0`
`System Version: macOS 13.3.1`

client/catai runs just fine! 
What's odd is that I run llama-node [inference.js](https://github.com/Atome-FE/llama-node/blob/main/example/js/llama-cpp/inference.js) just fine on this Mac.
Installing globally and using catai serve also works without error.

**Comment by ido-pluto** [comment]
Currently I am creating a new way to install models.

A work around is to copy full URL from `model-links.json`

```
npm run install-model https://my-model-link
```
The new way takes the models from `models.json` which is not fully checked  as of this moment.

**Comment by authcompanion** [comment]
OK cool - looking forward to the new way to install models. 👍 
My goal would be to try out this `ggmlv3` https://huggingface.co/TheBloke/WizardLM-7B-uncensored-GGML/tree/main

**Comment by ido-pluto** [comment]
ggmlv3 is supported now :)
