### ISSUE TITLE
<end> after sending any message in the web interface

### ISSUE THREAD

**Issue by Raikiri** [withcatai/catai#23]
**Describe the bug**
I have setup catai, downloaded a model, the web interface opens up, I see this in the console of the server:
```
new connection
```
but as soon as I type anything in the web interface, the circle starts spinning indefinitely and this pops up in the server log:
```
<end>
```

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - CatAI version 0.3.12
 - Node.js version 18.16.0

PS i clearly have no idea what i'm doing, so the problem is likely on my side, but I don't know what to try

**Comment by Raikiri** [comment]
Update: further testing revealed that the problem affects specifically ggml-vic7b-uncensored-q4_0.bin and does not affect ggml-vic7b-q4_0.bin

**Comment by ido-pluto** [comment]
Seems like a problem with the model, and the ui should show that the message ended.
