### ISSUE TITLE
catai serve exit with error: 132 (on MacOS M1 pro)

### ISSUE THREAD

**Issue by greenido** [withcatai/catai#25]
## Describe the bug
1. Install: catai install Vicuna-7B 
2. Run 'catai serve' 
3. Got an error 132 - As you can see below the full details.

## Screenshots
Got this:
```
catai $ catai serve
$ cd /usr/local/lib/node_modules/catai
$ npm start -- --production true --ui catai

> catai@0.3.12 start
> node src/index.js --production true --ui catai

/bin/bash: line 1: 49127 Illegal instruction: 4  npm start -- --production true --ui catai
/bin/bash: line 1: 49127 Illegal instruction: 4  npm start -- --production true --ui catai
    at file:///usr/local/lib/node_modules/catai/scripts/cli.js:69:27
    exit code: 132 (Illegal instruction)
```

----

## Desktop
 - OS: MacOS 13.4 M1 pro
 - Browser: chrome
 - CatAI version: 0.3.12
 - Node.js version: v19.8.1

**Comment by ido-pluto** [comment]
That is probably because you do not have enough memory available.
Check in the ActivityMonitor that there is a least 6GM of available memory and the memory pressure is green and try again.

**Comment by greenido** [comment]
I have over 20G of free memory (the physical memory is 32GB and the used is only 9)

**Comment by ido-pluto** [comment]
I could not reproduce this error,
I recommend you try this again from scratch just to be sure.

```
npm r -g catai
npm i -g catai
catai remove Vicuna-7B
catai install Vicuna-7B
``` 

If that still does not work, please open an issue on [node-llama](https://github.com/Atome-FE/llama-node/issues) GitHub page.

This version of CatAI, uses node-llama 0.1.5,
Maybe the creator of the package will know what causing this error.

BTW: Did other models work for you?

**Comment by greenido** [comment]
Yep - other models did work for me (but not on node). 
alpaca.cpp is working so I'm 'playing' with it for now.

I'll open an issue at node-llama.

Thank you for all the help 🙌🏾
It's really cool project you are starting here ;)

**Comment by ido-pluto** [comment]
Does [llama-cpp](https://github.com/ggerganov/llama.cpp) works for you?

**Comment by greenido** [comment]
Yes - It did.

**Comment by ido-pluto** [comment]
CatAI now uses a custom lib to connect to ggml models.
Try to update, and use a model listed in `catai ls`
