### ISSUE TITLE
Error on Win 11

### ISSUE THREAD

**Issue by dillfrescott** [withcatai/catai#27]
```
C:\Users\micro\Downloads>catai serve --ui chatGPT
$ cd C:\Users\micro\AppData\Roaming\npm\node_modules\catai
$ npm start -- --production true --ui chatGPT

> catai@0.3.12 start
> node src/index.js --production true --ui chatGPT

fatal runtime error: Rust cannot catch foreign exceptions
fatal runtime error: Rust cannot catch foreign exceptions
    at file:///C:/Users/micro/AppData/Roaming/npm/node_modules/catai/scripts/cli.js:69:27
    exit code: 9
```

**Comment by ido-pluto** [comment]
Please tell me what steps you did,
What CPU you have, and anything you think it's related

**Comment by dillfrescott** [comment]
Oh. I followed the steps from the instructions. I have an amd 5800X.

I can always reinstall it and try it again to see if maybe it will work

**Comment by ido-pluto** [comment]
Is this working now? if not please provide as many details as you can

**Comment by dillfrescott** [comment]
I apologize i recently switched to linux so I guess this issue is kinda moot. I will close it because I couldn't replicate it! :)
