### ISSUE TITLE
Unable to install `catai` onto an ARM development board

### ISSUE THREAD

**Issue by spectrachrome** [withcatai/catai#36]
**Describe the bug**

The installation of the package fails part-way. Node does not find an entrypoint in the `~/catai/models` directory, which suggests that something goes haywire in the installation machinery. I'm trying to test out the performance of the small 3B version of StableLM on an Odroid N2+ development board using CatAI.

```
-> % npm install -g catai
npm ERR! code 1
npm ERR! path /home/alarm/.nvm/versions/node/v20.6.0/lib/node_modules/catai
npm ERR! command failed
npm ERR! command sh -c node ./dist/cli/cli.js postinstall
npm ERR! CatAI Migrated to v0.3.13
npm ERR! node:internal/process/promises:289
npm ERR!             triggerUncaughtException(err, true /* fromPromise */);
npm ERR!             ^
npm ERR!
npm ERR! [Error: ENOENT: no such file or directory, scandir '/home/alarm/catai/models'] {
npm ERR!   errno: -2,
npm ERR!   code: 'ENOENT',
npm ERR!   syscall: 'scandir',
npm ERR!   path: '/home/alarm/catai/models'
npm ERR! }
npm ERR!
npm ERR! Node.js v20.6.0
```

The provided error message, `CatAI Migrated to v0.3.13`, is not of particular help to me.
Could you explain in more detail what this error message is about? 🙂

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - **OS**
 Arch Linux ARM (`Linux cinedroid 5.10.2-6-ARCH #1 SMP PREEMPT Mon Dec 28 21:22:54 AST 2020 aarch64 GNU/Linux`)
 - **Browser**
 N/A
 - **CatAI version [e.g. 0.3.10] (`catai --version`)**
 Latest release version on NPM, I guess.
 - **Node.js version [e.g 19] (`node --version`)**
 18 and 20

**Comment by ido-pluto** [comment]
It is an error related to the migration process between older versions of CatAI.

I will fix it in the next version. It fails, maybe the catai directory is different - I need to try it and check why it happens.

**Comment by ido-pluto** [comment]
The last release should fix that issue, try to run `catai update` again :)

**Comment by spectrachrome** [comment]
Thank you, that works beautifully! 🎉
