### ISSUE TITLE
How to pass computer resource information

### ISSUE THREAD

**Issue by schrummy14** [withcatai/catai#40]
Hello,
I am looking to see where/how cpu and/or gpu information is passed during server start but I am unable to find it.
Thank you

**Comment by ido-pluto** [comment]
Are you trying to configure CatAI only to use some CPU/GPU cores?
In general `llama.cpp` is the actual engine behind the scenes, you can configure with CatAI how many CPU/GPU cores and memory the model uses.

You can configure CatAI like this:

1. open the settings tab:
![image](https://github.com/withcatai/catai/assets/50456099/7361ca04-4e71-49bf-a24f-45aec6bacd12)

2. Add custom settings, which you can find here: https://withcatai.github.io/node-llama-cpp/types/LlamaModelOptions.html

4. Restart CatAI
![image](https://github.com/withcatai/catai/assets/50456099/a1307774-f882-49a0-aeb7-27cc168f4b2e)

**Comment by schrummy14** [comment]
Hello,

I am trying to get the model to utilize all of the cpu/gpu that I have available...
Looking at the utilization, `node` is using 6 cores (of 16) and ~13% of a v100 gpu.
![image](https://github.com/withcatai/catai/assets/25237907/a83584ee-905e-4d0c-a9ce-0ca8677a54af)
![image](https://github.com/withcatai/catai/assets/25237907/f21cb8df-3a65-4085-84f5-b49a75973191)

I have tried altering some of the settings but I wasn't able to see a difference.
By chance is it because of the model that I am using?
`vicuna-7b-v1.5-q4_1`

Thank you.

**Comment by ido-pluto** [comment]
Yes, this may be related. The binding of `node-llama-cpp` has some bugs with the configuration.
This binding allows you to use `ggmlV3` (legacy format).

The recommended format is `gguf` (`node-llama-cpp-v2`), 
If you want to utilize more VRAM you should use a bigger model, such as
- `llama-2-13b-chat-limarp-v2-merged-q3_k_s`
- `phind-codellama-34b-q3_k_s`

You can check this page for more models: https://huggingface.co/TheBloke

Most GGUF models are supported, you can install a custom model by coping the model link to `catai install`

![image](https://github.com/withcatai/catai/assets/50456099/ad802917-52d9-4dea-8be9-f603f3a88ae0)

The more parameter the model the more resources it utilizes, so this model (70B) https://huggingface.co/TheBloke/ARIA-70B-V2-GGUF

Can be pretty heavy.


If a model split into files like https://huggingface.co/TheBloke/Falcon-180B-GGUF/tree/main
You can install it like this:

`canai install model-part-a.gguf,model-part-b.gguf`

I have not tried this method yet, so if there is a problem feel free to report it :)

**Comment by schrummy14** [comment]
Ok. I'll continue to look into it.
For the gif that is in the documentation, would you be able to tell me what model was used and about how long the answer took to generate? I feel that what I am seeing is slower than what is to be expected.
Thank you again.

**Comment by ido-pluto** [comment]
This git was generated from screen recording in mac pro m1. llama.cpp has spesifict optimization for mac silicon.
If I remember right this was from `vicuna-13b-v1.5-q4_1` (but older version of the model).
I will soon update the models index to support vicuna with GGUF (gguf have more optimizations).

Are your cuda working when the model generating tokens?

**Comment by ido-pluto** [comment]
I uploaded new models, in my Mac token/s is faster than in the gif, I use `vicuna-7b-16k-q4_k_s`


https://github.com/withcatai/catai/assets/50456099/7a971dd3-8fd5-45d4-840a-2325d03d2de4

**Comment by schrummy14** [comment]
Thank you.
I'll need to go back and see what is happening on my side as it is much slower than what you are showing.
I'll close this out.
Thank you again.
