### ISSUE TITLE
Failed to load prebuilt binary for platform "linux" "arm64".

### ISSUE THREAD

**Issue by foertel** [withcatai/catai#48]
Hey,

when installing `npm install -g catai` the catai Server fails conversations stating: `Failed to load prebuilt binary for platform "linux" "arm64". Error: Error: /usr/local/lib/node_modules/catai/node_modules/node-llama-cpp/llamaBins/linux-arm64/llama-addon.node: cannot open shared object file: No such file or directory`.

The file is actually there. 
```
# ls -la  /usr/local/lib/node_modules/catai/node_modules/node-llama-cpp/llamaBins/linux-arm64/llama-addon.node
-rw-r--r-- 1 root root 1184376 Oct  6 10:32 /usr/local/lib/node_modules/catai/node_modules/node-llama-cpp/llamaBins/linux-arm64/llama-addon.node
```

**Comment by foertel** [comment]
I can fix it by running `node_modules/.bin/node-llama-cpp download`. But from what I've read, it's supposed to build the right bin on it's own, isn't it?

**Comment by ido-pluto** [comment]
Yes, it should have prebuild node addon.
I will check that :)

**Comment by ido-pluto** [comment]
A new version of node-llama-cpp has been released.
Please update with `catai update` and try again.

Is this issue solved?

**Comment by foertel** [comment]
Yup, works now. Thanks a bunch. :)
