### ISSUE TITLE
configure website down

### ISSUE THREAD

**Issue by Gasiorrr** [withcatai/catai#51]
hi i like configure catai.

https://withcatai.github.io/node-llama-cpp/types/LlamaModelOptions.html

but this website dont work.

can you provide me some good configure to your bot?

PS.

i lunch this catai github program on S8+ just install git and cmake and the catai run on termux normal :)

**Comment by ido-pluto** [comment]
This website has been changed a bit, you can look here instead:
https://withcatai.github.io/node-llama-cpp/api/type-aliases/LlamaContextOptions
https://withcatai.github.io/node-llama-cpp/api/type-aliases/LLamaChatPromptOptions

A good configuration really depends on your needs:
 - if you need that model to remember more you may want to increase the context
 - If it is slow try to increase/decrease the thread amount
 - You want it to be more random, increase the temperature

I am glad to hear it, I actually did that too :)
