### ISSUE TITLE
Does not work on ubuntu 22.04 & node 20

### ISSUE THREAD

**Issue by Temtaime** [withcatai/catai#52]
Please refer to the [troubleshooting](https://github.com/ido-pluto/catai/blob/main/docs/troubleshooting.md) before opening an issue. You might find the solution there.

**Describe the bug**
Followed instructions, when `catai up` is used it only opens a page for 1 time, then process exits.

**Screenshots**
```
$ catai up
CatAI client on http://127.0.0.1:3000
New connection
$ echo $?
0
```

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser [e.g. chrome, safari] Chrome
 - CatAI version [e.g. 0.3.10] (`catai --version`) 3.0.0
 - Node.js version [e.g 19] (`node --version`) 20

**Comment by ido-pluto** [comment]
It happened before when I did not have enough RAM for the model to run. 
Which model do you try to run?
How many GB of memory do you have?
What is the CPU of your computer?

**Comment by Temtaime** [comment]
I have `64gb` ram, tried `wizard-vicuna-30b-uncensored-q4_k_s`, cpu is `ryzen 5900x`.

**Comment by ido-pluto** [comment]
Do other models work for you?

Try this:

```
# cd to catai directory
cd `where catai | rev | cut -c10- | rev`/lib/node_modules/catai/

# update node-llama-cpp to the latest version
npm i node-llama-cpp@latest
```

If it also does not work, we can try to recompile it:
```
npx node-llama-cpp download
```

After that tell me if it works, I want to check the issue more deeply :)

**Comment by Temtaime** [comment]
Hello

`npm i node-llama-cpp@latest` executed without errors, but it still was not working

After recompiling with `npx node-llama-cpp download` it started to work, thanks !

**Comment by 0xGoenka** [comment]
Not working on Ubuntu 22.04.3 LTS and node 18

**Comment by 0xGoenka** [comment]
![image](https://github.com/withcatai/catai/assets/11486742/ae62b731-2477-4925-839a-06f97ce59231)

**Comment by ido-pluto** [comment]
On it, I think the cpp binaries for AMD do not work properly

**Comment by ido-pluto** [comment]
You can fix this issue, by using catai beta and rebuilding the binaries
```
npm i -g catai@beta
catai cpp
```
