### ISSUE TITLE
logo in docs have 2 404 errors

### ISSUE THREAD

**Issue by LoveMeWithoutAll** [withcatai/catai#54]
Please refer to the [troubleshooting](https://github.com/ido-pluto/catai/blob/main/docs/troubleshooting.md) before opening an issue. You might find the solution there.

**Describe the bug**
You must be careful on logo image 404 error!

**Screenshots**
<img width="546" alt="image" src="https://github.com/withcatai/catai/assets/4844714/93d53253-41f7-45ec-ad70-09be70c36c04">

<img width="1048" alt="image" src="https://github.com/withcatai/catai/assets/4844714/f4c09eac-f1f2-4600-a127-6df857927476">

**Desktop (please complete the following information):**
 - OS: [e.g. windows, macOS, linux]
 - CatAI version [e.g. 0.3.10] (`catai --version`)
 - Node.js version [e.g 19] (`node --version`)

**Comment by ido-pluto** [comment]
I will check that, thank you for reposting :)
