### ISSUE TITLE
Is there a way to specify a path where to store model ?

### ISSUE THREAD

**Issue by 0xGoenka** [withcatai/catai#57]

**Comment by molander** [comment]
Same! What I ended up doing was:

* Moved the default model folder catai creates (just in case):
```
  mv ~/catai/models{,.orig}
  ln -nfs ~/projects/models ~/catai/models
```
  
  But I still needed to "install" them via catai, probably to update the json file with the model options:
`  catai i /original/path/to/model/modelname
`  
  And then they fired right up!
  
  FYI: Great project, thank you! MEOW!

**Comment by ido-pluto** [comment]
Actually, there is,

https://withcatai.github.io/catai/interfaces/_internal_.Config.html#CATAI_DIR

It will be better documented in the future.

There is an environment variable named `CATAI_DIR`, that does exactly that :)

**Comment by 0xGoenka** [comment]
Ty you solved my issue
