### ISSUE TITLE
How to install and run catai from packages?

### ISSUE THREAD

**Issue by UserItaly** [withcatai/catai#58]
I'd like to install CatAI from the GitHub source rather than using the npm servers, because I want to make some modifications to the interface.

However, I'm having trouble doing so.
I've recently started studying programming. 

How can I go about this? 
I've tried downloading the package and installing it with "npm install" in /server/ folder, but I'm not sure how to run it after installation. :(

**Comment by ido-pluto** [comment]
Run this:

```
npm install --ignore-scripts

npm run cli help
```

The installation without `--ignore-scripts` can cause problems at first run (the project is not compiled yet, so the port-install script can not run)

The `cli` command will compile the project and enable you to run the CatAI's CLI locally so you can test your changes
