### ISSUE TITLE
Feedback: Model discovery and installation 

### ISSUE THREAD

**Issue by os6sense** [withcatai/catai#7]
Running install with an unrecognised model gives the following output:

```
➜  models catai install gpt4all                                                                                                                                                                  
$ cd /usr/local/lib/node_modules/catai                                                                                                                                                                     
Model unknown, we will download with template URL. You can also try one of thous:7B, 13B, 30B, Vicuna-7B, Vicuna-7B-Uncensored, Vicuna-13B, Stable-Vicuna-13B, Wizard-Vicuna-7B, Wizard-Vicuna-7B-Uncensored, Wizard-Vicuna-13B, OpenAssistant-30B
```
Outputting a list of available models is excellent but perhaps also worth adding a `catai install --list` or similar command?

Also observe that the output appears to make no sense ... `thous:7B`? And what are the 7B,13B,30B models? (edit) Ahhh, the original llama models, doh!

**Comment by ido-pluto** [comment]
Yes, it is a bit confusing naming something with 7B.
This is planned to be changed in the feature.

It is a good idea to list all the available models in a formatted way, with a simple command.

Thanks for sharing this :)

**Comment by os6sense** [comment]
No worries, and thanks for this project. Obviously there is a lot of work going on in the LLM area and having something simple that doesn't take days of reading to understand is bound to increase interest and the ability of people to experiment. 

Just downloading the models is an adventure given that it is not obvious that huggingface models are just git repos, nor is it obvious exactly what formats will work. `catai install` is bang where the complexity should lay.
