### ISSUE TITLE
[Feature Request] Stop button for long running executions

### ISSUE THREAD

**Issue by Koliham** [withcatai/catai#9]
A "Stop" button to stop long running execution would be good.

**Comment by ido-pluto** [comment]
Will be added in feature versions :)

**Comment by ido-pluto** [comment]
Update: already been implemented on CatAI's end, waiting for [node-llama](https://github.com/Atome-FE/llama-node/issues/41#issuecomment-1542548518) implementation

**Comment by ido-pluto** [comment]
@Koliham 
Checkout version 0.3.6
